# Generated by Django 4.2.6 on 2023-10-27 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='merchant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
